spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    url: ${FLYWAY_URL}
    user: ${FLYWAY_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  thymeleaf:
    cache: false

logging:
  level:
    com.sportscamp: DEBUG
    org.springframework.security: DEBUG
